SELECT * FROM Students
WHERE 
(Name IS NULL AND No_A IS NOT NULL AND No_B IS NOT NULL AND No_C IS NOT NULL)
OR
(Name IS NOT NULL AND No_A IS NULL AND No_B IS NOT NULL AND No_C IS NOT NULL)
OR
(Name IS NOT NULL AND No_A IS NOT NULL AND No_B IS NULL AND No_C IS NOT NULL)
OR
(Name IS NOT NULL AND No_A IS NOT NULL AND No_B IS NOT NULL AND No_C IS NULL)

